formation_metier/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from schema_graph.views import Schema

from formation_metier.api import urls_api
from formation_metier.views import ListeFormationView, HomeView, NouvelleFormationFormView, DetailFormation, \
    DetailSeanceView, ModificationFormationView, ModificationSeanceView, NouvelleSeanceFormView, SuppressionSeance, \
    SuppressionFormation, SelectionParticipantAutoComplete, SuppressionMultiplesInscriptionsParFormateur, \
    SuppressionInscriptionParParticipant, InscriptionFormationPourParticipant, InscriptionSeancePourParticipantView, \
    SuppressionUniqueInscriptionParFormateurView, ListeParticipantsFormationView

app_name = 'formation_metier'
urlpatterns = [
    path('', HomeView.as_view(), name=HomeView.name),

    # list_view
    path('liste_formations/', ListeFormationView.as_view(), name=ListeFormationView.name),
    path('liste_participants/<uuid:formation_id>', ListeParticipantsFormationView.as_view(),
         name=ListeParticipantsFormationView.name),

    # detail_view
    path('formation/<uuid:formation_id>/', DetailFormation.as_view(), name=DetailFormation.name),
    path('formation/seance/<uuid:seance_id>/', DetailSeanceView.as_view(), name=DetailSeanceView.name),

    # new_view
    path('nouvelle_formation/', NouvelleFormationFormView.as_view(), name=NouvelleFormationFormView.name),
    path('formation/nouvelle_seance/<uuid:formation_id>/', NouvelleSeanceFormView.as_view(),
         name=NouvelleSeanceFormView.name),

    # inscription_pour_participant_view
    path('inscription/formation/<uuid:formation_id>/', InscriptionFormationPourParticipant.as_view(),
         name=InscriptionFormationPourParticipant.name),
    path('inscription/seance/<uuid:seance_id>/', InscriptionSeancePourParticipantView.as_view(),
         name=InscriptionSeancePourParticipantView.name),

    # update_view
    path('formation/modification/<uuid:formation_id>/', ModificationFormationView.as_view(),
         name=ModificationFormationView.name),
    path('formation/seance/modification/<uuid:seance_id>/', ModificationSeanceView.as_view(),
         name=ModificationSeanceView.name),

    # delete_view
    path('formation/suppression/<uuid:formation_id>/', SuppressionFormation.as_view(), name=SuppressionFormation.name),
    path('formation/seance/suppression/<uuid:seance_id>/', SuppressionSeance.as_view(), name=SuppressionSeance.name),
    path('formation/seance/inscription_formateur/suppression_multiple/',
         SuppressionMultiplesInscriptionsParFormateur.as_view(),
         name=SuppressionMultiplesInscriptionsParFormateur.name
         ),
    path('formation/seance/inscription_participant/suppression/', SuppressionInscriptionParParticipant.as_view(),
         name=SuppressionInscriptionParParticipant.name),
    path('formation/seance/inscription_formateur/suppression_unique/<uuid:inscription_id>',
         SuppressionUniqueInscriptionParFormateurView.as_view(),
         name=SuppressionUniqueInscriptionParFormateurView.name),

    # Autocomplete Widget

    path('autocompletePerson/', SelectionParticipantAutoComplete.as_view(), name=SelectionParticipantAutoComplete.name),

    # API
    path('', include(urls_api)),

    # auth
    path('accounts/login/', auth_views.LoginView.as_view()),

    # graph_models
    path("schema/", Schema.as_view(), name='schemaModels'),
]

formation_metier/models/formation.py
import uuid

from django.contrib import admin
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import UniqueConstraint
from django.urls import reverse

from formation_metier.enums.roles_osis_enum import ROLES_OSIS_CHOICES
from module_formation.settings import URL_BASE_MODULE

MAX_LENGTH_CODE = 6
MAX_LENGTH_NAME = 50
MAX_LENGTH_DESCRIPTION = 200
MAX_LENGTH_PUBLIC_CIBLE = 200


class Formation(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    code = models.CharField(
        max_length=MAX_LENGTH_CODE,
        blank=False,
        validators=[
            RegexValidator(r'^[A-Za-z]{1,4}[0-9]{1,2}$')
        ]
    )
    name = models.CharField(
        max_length=MAX_LENGTH_NAME,
        blank=False
    )
    description = models.CharField(
        max_length=MAX_LENGTH_DESCRIPTION,
        blank=False
    )
    public_cible = models.CharField(
        max_length=MAX_LENGTH_PUBLIC_CIBLE,
        choices=ROLES_OSIS_CHOICES,
        default=None
    )

    class Meta:
        constraints = [
            UniqueConstraint(fields=['code'], name='unique_formation_code'),
        ]

    def __str__(self):
        return f"{self.name}"

    def get_inscription_lien(self):
        return URL_BASE_MODULE + reverse(
            'formation_metier:inscription_formation',
            kwargs={
                'formation_id': self.id
            }
        )


class FormationAdmin(admin.ModelAdmin):
    fieldsets = [
        ('code', {'fields': ['code']}),
        ('name', {'fields': ['name']}),
        ('description', {'fields': ['description']}),
        ('public_cible', {'fields': ['public_cible']})
    ]
    list_display = (
        'id',
        'name',
        'code',
        'description',
        'public_cible'
    )

formation_metier/models/inscription.py
import uuid

from django.contrib import admin
from django.db import models

from formation_metier.models.employe_uclouvain import EmployeUCLouvain
from formation_metier.models.seance import Seance


class Inscription(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    seance = models.ForeignKey(
        Seance,
        on_delete=models.CASCADE,
        blank=False
    )
    participant = models.ForeignKey(
        EmployeUCLouvain,
        on_delete=models.CASCADE,
        blank=False
    )
    inscription_date = models.DateTimeField(
        auto_now_add=True,
        blank=False
    )

    class Meta:
        unique_together = (
            'seance',
            'participant',
        )


class InscriptionAdmin(admin.ModelAdmin):
    fieldsets = [
        ('seance', {'fields': ['seance']}),
        ('participant', {'fields': ['participant']}),
    ]
    list_display = (
        'id',
        'seance',
        'participant',
        'inscription_date'
    )

formation_metier/views/delete_formation_view.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic

from formation_metier.models.formation import Formation


class DeleteFormation(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    permission_required = ['formation_metier.delete_formation', 'formation_metier.access_to_formation_fare']
    model = Formation
    pk_url_kwarg = "formation_id"

    def get_success_url(self):
        success_message = f'La formation {self.object.name} a été supprimée.'
        messages.success(self.request, success_message)
        return '/list_formation'

formation_metier/views/delete_seance_view.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.views import generic

from formation_metier.models.seance import Seance


class DeleteSeance(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    permission_required = ['formation_metier.delete_seance', 'formation_metier.access_to_formation_fare']
    model = Seance
    pk_url_kwarg = "seance_id"

    def get_success_url(self):
        success_message = f'La seance pour la formation {self.object.formation.name} organisé le {self.object.seance_date.__format__("%d/%m/%Y")} à {self.object.time_format()} a été supprimée.'
        messages.success(self.request, success_message)
        return reverse('formation_metier:detail_formation', kwargs={'formation_id': self.object.formation.id})

formation_metier/views/detail_formation.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import generic

from formation_metier.models.formation import Formation


class DetailFormation(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    permission_required = ['formation_metier.view_formation', 'formation_metier.view_seance',
                           'formation_metier.access_to_formation_fare']
    model = Formation
    template_name = 'formation_metier/detail_formation.html'
    context_object_name = "formation"
    pk_url_kwarg = 'formation_id'
    name = 'detail_formation'

    def get_queryset(self):
        return super().get_queryset().filter(id=self.kwargs['formation_id']).prefetch_related(
            'seance_set',
            'seance_set__register_set',
            'seance_set__formateur',
        )

formation_metier/views/detail_formation_view.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Prefetch, Exists, OuterRef
from django.views import generic

from formation_metier.models.formation import Formation
from formation_metier.models.seance import Seance


class DetailFormation(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    permission_required = [
        'formation_metier.view_formation',
        'formation_metier.view_seance',
        'formation_metier.access_to_formation_fare'
    ]
    model = Formation
    template_name = 'formation_metier/detail_formation.html'
    context_object_name = "formation"
    pk_url_kwarg = 'formation_id'
    name = 'detail_formation'

    def get_queryset(self):
        date = datetime.now()
        return super().get_queryset().filter(
            id=self.kwargs['formation_id']
        ).annotate(
            a_seance_passee=Exists(
                Seance.objects.filter(
                    seance_date__lt=date,
                    formation__id=self.kwargs['formation_id']
                )
            )
        ).prefetch_related(
            Prefetch(
                'seance_set',
                queryset=Seance.objects.order_by('seance_date').annotate(est_seance_passee=Exists(
                    Seance.objects.filter(
                        seance_date__lt=date,
                        id=OuterRef('pk')
                    ),
                ))
            ),
            'seance_set__inscription_set',
            'seance_set__formateur',
        )

formation_metier/views/home_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic


class HomeView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'formation_metier/home.html'
    name = 'home'

formation_metier/views/list_formation_view.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import generic

from formation_metier.models.formation import Formation


class ListFormationView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = ['formation_metier.view_formation', 'formation_metier.access_to_formation_fare']
    model = Formation
    template_name = "formation_metier/list_formation.html"
    context_object_name = 'formation_list'
    name = 'list_formation'
    queryset = Formation.objects.all()

formation_metier/views/liste_formation_view.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import generic

from formation_metier.models.formation import Formation


class ListeFormationView(LoginRequiredMixin, generic.ListView):
    model = Formation
    template_name = "formation_metier/liste_des_formation.html"
    context_object_name = 'formation_liste'
    name = 'liste_formation'
    queryset = Formation.objects.all().order_by('name')

formation_metier/views/liste_formations_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Exists, OuterRef
from django.views import generic

from formation_metier.models.formation import Formation
from formation_metier.models.inscription import Inscription


class ListeFormationView(LoginRequiredMixin, generic.ListView):
    model = Formation
    template_name = "formation_metier/liste_formations.html"
    context_object_name = 'liste_formations'
    name = 'liste_formations'

    def get_queryset(self):
        return super().get_queryset().order_by('name').annotate(
            est_inscrit_formation=Exists(
                Inscription.objects.filter(
                    participant=self.request.user.employeuclouvain,
                    seance__formation=OuterRef('pk')
                )
            )
        )

    def get_context_data(self, *, object_list=None, **kwargs):
        return {**super().get_context_data(object_list=object_list, **kwargs),
                'current_user_est_formateur': self.request.user.groups.filter(name='FormateurGroup').exists()
                }

formation_metier/views/liste_participants_formation_view.py
from django.views import generic

from formation_metier.models.employe_uclouvain import EmployeUCLouvain
from formation_metier.models.formation import Formation


class ListeParticipantsFormationView(generic.ListView):
    model = EmployeUCLouvain
    name = "liste_participants_formations"
    context_object_name = "liste_participants"
    template_name = "formation_metier/liste_participants_formation.html"
    pk_url_kwarg = "formation_id"

    def get_queryset(self):
        return super().get_queryset().filter(
            inscription__seance__formation_id=self.kwargs["formation_id"]).distinct().order_by('name')

    def get_context_data(self, *, object_list=None, **kwargs):
        return {**super().get_context_data(object_list=object_list, **kwargs),
                'formation': Formation.objects.get(id=self.kwargs["formation_id"])
                }

formation_metier/views/modification_formation_view.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.views import generic

from formation_metier.models.formation import Formation


class ModificationFormationView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin,
                                generic.edit.UpdateView):
    permission_required = [
        'formation_metier.change_formation',
        'formation_metier.access_to_formation_fare'
    ]
    model = Formation
    fields = [
        'name',
        'code',
        'description',
        'public_cible'
    ]
    template_name = 'formation_metier/modification_formation_form.html'
    pk_url_kwarg = "formation_id"
    success_message = 'La formation %(name)s a été modifiée.'
    name = 'modification_formation'

    def get_success_url(self):
        return reverse(
            'formation_metier:detail_formation',
            kwargs={
                'formation_id': self.kwargs['formation_id']
            }
        )

formation_metier/views/new_formation_form_view.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.views import generic

from formation_metier.models.formation import Formation
from formation_metier.forms.new_formation_form import NewFormationForm


class NewFormationFormView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    permission_required = ['formation_metier.add_formation', 'formation_metier.access_to_formation_fare']
    model = Formation
    template_name = 'formation_metier/new_formation_form.html'
    form_class = NewFormationForm
    success_url = '/list_formation'
    name = 'new_formation'

    def form_valid(self, form):
        messages.success(self.request, 'La formation {} a été ajouté.'.format(form.cleaned_data['name']))
        return super().form_valid(form)

formation_metier/views/nouvelle_seance_form_view.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from formation_metier.models.formation import Formation
from formation_metier.models.seance import Seance
from formation_metier.forms.nouvelle_seance_form import NouvelleSeanceForm


class NouvelleSeanceFormView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    permission_required = [
        'formation_metier.add_seance',
        'formation_metier.access_to_formation_fare'
    ]
    model = Seance
    template_name = 'formation_metier/nouvelle_seance_form.html'
    form_class = NouvelleSeanceForm
    pk_url_kwarg = "formation_id"
    name = 'nouvelle_seance'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["formation_id"] = self.kwargs['formation_id']
        return context

    def get_success_url(self):
        return reverse(
            'formation_metier:detail_formation',
            kwargs={'formation_id': self.kwargs['formation_id']}
        )

    def form_valid(self, form):
        formation_object = get_object_or_404(Formation, id=self.kwargs['formation_id'])
        form.instance.formation = formation_object
        messages.success(
            self.request,
            f"La seance du {form.cleaned_data['seance_date'].__format__('%d/%m/%Y')}"
            f" à {form.cleaned_data['seance_date'].__format__('%Hh%M')} a été ajouté."
        )
        return super().form_valid(form)

formation_metier/templates/formation_metier/detail_formation.html
{% extends 'formation_metier/base.html' %}
{% load bootstrap3 %}
{% load static %}
{% load l10n %}

{% block content %}
    {% include 'formation_metier/suppression_formation_modal.html' %}
    {% include 'formation_metier/generation_lien_inscription_formation_modal.html' %}
    <ol class="breadcrumb">
        <li><a href="{% url 'formation_metier:home' %}" id="lnk_home_osis"><span class="glyphicon glyphicon-home"
                                                                                 aria-hidden="true"></span></a></li>
        <li>
            <a href="{% url 'formation_metier:liste_formations' %}">
                Liste des formations
            </a>
        </li>
        <li class="active">
            Formation
        </li>
    </ol>
    {% if form.errors %}
        <div class="alert alert-danger alert-dismissible alert-link">
            {{ form.non_field_errors }}
        </div>
    {% endif %}
    {% if messages %}
        <div class="alert alert-success alert-dismissible alert-link">
            <ul class="messages">
                {% for message in messages %}
                    <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}>
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-10">
            <h2>Formation : {{ formation.name }} </h2>
        </div>
        <div class="col-md-2" style="margin-top: 20px">
            <div class="btn-group pull-right">
                <button id="btn-action" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Actions
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-large row ">
                    <li>
                        <a href="{% url 'formation_metier:nouvelle_seance' formation.id %}" class="no_spinner">
                            <form method="post" style="margin: 0">Ajouter une nouvelle seance</form>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'formation_metier:modification_formation' formation.id %} "
                           class="no_spinner">
                            <form method="post" style="margin: 0">Modifier la formation</form>
                        </a>
                    </li>
                    <hr/>
                    <li>
                        <a href="#" data-toggle="modal" data-target="#GenerationLienInscriptionFormationModal">
                            Générer un lien d'inscription
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'formation_metier:liste_participants_formations' formation.id %} "
                           class="no_spinner">
                            <form method="post" style="margin: 0">Liste des participants</form>
                        </a>
                    </li>
                    <hr/>
                    <li>
                        <a href="#" data-toggle="modal" data-target="#formationDeleteModal">Supprimer la
                            formation</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="panel panel-default" style="padding: 10px">
        <p>Code : {{ formation.code }}</p>
        <p>Description : {{ formation.description }}</p>
        <p>Public cible : {{ formation.get_public_cible_display }}</p>
    </div>
    {% if formation.seance_set.count > 0 %}
        <div class="panel-group">
            <div class="panel panel-default" id="seances_futures">
                <div class="panel-heading">
                    <h3 class="panel-title">Séances ouvertes</h3>
                </div>
                <div class="panel-body">
                    <table class="table" id="seance_ouverte_table">
                        <thead>
                        <tr style="font-weight: bold">
                            <td>Date</td>
                            <td>Heure</td>
                            <td>Durée</td>
                            <td>Local</td>
                            <td>Participants</td>
                            <td>Nom du formateur</td>
                        </tr>
                        </thead>
                        <tbody>
                        {% for seance in formation.seance_set.all %}
                            {% if not seance.est_seance_passee %}
                                <tr>
                                    <td>
                                        <a href="{% url 'formation_metier:detail_seance' seance.id %}">
                                            {{ seance.seance_date|date:"l j F o" }}
                                        </a>
                                    </td>
                                    <td>{{ seance.time_format }}</td>
                                    <td>{{ seance.duree }}</td>
                                    <td>{{ seance.local }}</td>
                                    <td>{{ seance.inscription_set.count }}/{{ seance.participant_max_number }}</td>
                                    <td>
                                        {% for formateur in seance.formateur.all %}
                                            {{ formateur }}
                                            <br>
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            {% if formation.a_seance_passee %}
                <div class="panel panel-default" id="seances_terminee">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            <a class="accordion-toggle collapsed" data-toggle="collapse" href="#pannel_seance_fermee"
                               aria-expanded="false" aria-controls="pannel_seance_fermee">
                                Séances terminées
                            </a>
                        </h3>
                    </div>
                    <div class="panel-body collapse" id="pannel_seance_fermee">
                        <table class="table" id="seance_fermee_table" style="width: 100%">
                            <thead>
                            <tr style="font-weight: bold">
                                <td>Date</td>
                                <td>Heure</td>
                                <td>Durée</td>
                                <td>Local</td>
                                <td>Participants</td>
                                <td>Nom du formateur</td>
                            </tr>
                            </thead>
                            <tbody>
                            {% for seance in formation.seance_set.all %}
                                {% if seance.est_seance_passee %}
                                    <tr>
                                        <td>
                                            <a href="{% url 'formation_metier:detail_seance' seance.id %}">
                                                {{ seance.seance_date|date:"l j F o" }}
                                            </a>
                                        </td>
                                        <td>{{ seance.time_format }}</td>
                                        <td>{{ seance.duree }}</td>
                                        <td>{{ seance.local }}</td>
                                        <td>{{ seance.inscription_set.count }}/{{ seance.participant_max_number }}</td>
                                        <td>
                                            {% for formateur in seance.formateur.all %}
                                                {{ formateur }}
                                                <br>
                                            {% endfor %}
                                        </td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% endif %}
        </div>
    {% else %}
        <div class="panel panel-default">
            <div class="panel-body">
                <p> Il n'y a pas de seance organisé pour la formation : {{ formation.name }}</p>
            </div>
        </div>
    {% endif %}
{% endblock %}
{% block script %}
    <script>
        let dataTableSeanceOuverteConfig = {
            paging: false,
            orderMulti: true,
            info: false,
            searching: true,
            processing: false,
        }
        $(document).ready(function () {
            $('#seance_ouverte_table').DataTable(dataTableSeanceOuverteConfig);
            $('#seance_fermee_table').DataTable(dataTableSeanceOuverteConfig);
        });
    </script>
{% endblock %}

formation_metier/templates/formation_metier/generation_lien_inscription_formation_modal.html
{% load bootstrap3 %}
{% load static %}
<script src="{% static '/formation_metier/copier_lien_inscription.js' %}"></script>
<div class="modal fade" id="GenerationLienInscriptionFormationModal" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Lien d'insciption à la formation pour les participants</h5>
            </div>
            <div class="modal-body">
                <div class="modal-body">
                    <a href="{{ formation.get_inscription_lien }}">
                        <span id="lien_inscription">{{ formation.get_inscription_lien }}</span>
                    </a>
                <button id="btn_copier_lien_inscription_seance" class="btn btn-primary" onclick="CopierText()">Copier le lien</button>
            </div>
            </div>
        </div>
    </div>
</div>

formation_metier/templates/formation_metier/list_formation.html
{% extends 'formation_metier/base.html' %}
{% load est_membre_du_groupe %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'formation_metier:home' %}" id="lnk_home_osis"><span class="glyphicon glyphicon-home"
                                                                                 aria-hidden="true"></span></a></li>
        <li class="active">
            Liste des formation
        </li>
    </ol>
    <div class="page-header">
        <div class="row">
            <div class="col-md-10">
                <h2>Formation organisée</h2>
            </div>
            <div class="col-md-2" style="margin-top: 20px">
                <div class="btn-group pull-right">
                    <button id="btn-action" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="true">
                        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-large row text-right pull-right">
                        {% if user|has_group:'FormateurGroup' %}
                            <li>
                                <a href="{% url 'formation_metier:new_formation' %}">Nouvelle formation</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    {% if messages %}
        <div class="alert alert-success alert-dismissable alert-link">
            <ul class="messages">
                {% for message in messages %}
                    <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <div class="panel panel-default">
        <div class="panel-body">
            {% if formation_list %}
                <table class="table">
                    <thead>
                    <tr>
                        <td>Nom</td>
                        <td>Code</td>
                        <td>Public cible</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for formation in formation_list %}
                        <tr>
                            <td>
                                <a href="{% url 'formation_metier:detail_formation' formation.id %}">
                                    {{ formation.name }}
                                </a>
                            </td>
                            <td>
                                {{ formation.code }}
                            </td>
                            <td>
                                {{ formation.get_public_cible_display }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <span> Il n'y a pas de formation organisée</span>
            {% endif %}

        </div>
    </div>
{% endblock %}